[package]
name = "datapipe"
version = "0.1.4"
edition = "2024"
authors = ["Richard Scott McNew <richard.scott.mcnew@outlook.com>"]
description = "Stream data from here to there"
license = "AGPL-3.0-only"
repository = "https://github.com/rmcnew/datapipe"
documentation = "https://docs.rs/datapipe"


[lib]
crate-type = ["lib"]

[dependencies]
bytes = { version = "1.8.0", features = ["serde"] }
chacha20poly1305 = { version = "0.10.1", features = ["alloc", "stream"] }
clap = { version = "4.5.21", features = ["derive"] }
log = { version = "0.4.22", features = ["serde"] }
log4rs = "1.3.0"
rand = "0.9.0"
rcgen = { version = "0.13.2", features = ["crypto", "pem"] }
reqwest = { version = "0.12.9", features = ["charset", "gzip", "http2", "json", "rustls-tls"], default-features = false }
rustls = { version = "0.23.25", features = ["ring", "logging", "std", "tls12"], default-features = false }
rustls-pemfile = "2.2.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
thiserror = "2.0.3"
tokio = { version = "1.41.1", features = ["full"] }
tokio-rustls = { version = "0.26.0", default-features = false, features = ["ring"] }
url = { version = "2.5.3", features = ["serde"] }
webpki-roots = "0.26.6"
